helpdesc/helpdesc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name="home"),
    path('accounts/', include('accounts.urls')),
    path('tickets/', include('tickets.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helpdesc/tickets/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.TicketsListView.as_view(), name="tickets"),
    path('knowledges/', views.KnowledgesListView.as_view(), name="knowledges"),
    path('create/', views.CreateTicketView.as_view(), name="create_ticket"),
    path('themes/', views.get_themes, name="themes"),
    path('create/knowledge/', views.CreateKnowledge.as_view(), name="create_knowledge"),
    path('comment/<int:pk>/', views.CreateComment.as_view(), name="create_comment"),
    path('close/<int:pk>/', views.CloseTicket.as_view(), name="close_ticket"),
    path('inprogress/<int:pk>/', views.ChangeStatusToInProgress.as_view(), name="inprogress"),
    path('detail/<int:pk>/', views.TicketDetail.as_view(), name="detail_ticket"),
]

helpdesc/tickets/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class Status(models.TextChoices):
    OPEN = 'open', _('Open')
    IN_PROGRESS = 'in_progress', _('In Progress')
    CLOSED = 'closed', _('Closed')

class Priority(models.IntegerChoices):
    LOW = 3, _("Low")
    MEDIUM = 2, _("Medium")
    HIGH = 1, _("High")


class Ticket(models.Model):
    """Тикеты"""   
    title = models.CharField(max_length=200)
    description = models.TextField("Описание")
    status = models.CharField(
        max_length=20, choices=Status.choices, default=Status.OPEN
    )
    priority = models.PositiveSmallIntegerField(
        choices=Priority.choices, db_index=True, default=Priority.MEDIUM
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='created_tickets', null=True)
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='assigned_tickets', null=True, blank=True)


    def __str__(self):
        return self.title
    

class Comment(models.Model):
    """Коммменты"""
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"comment to {self.ticket} ticket"


class Theme(models.Model):
    """Темы"""
    name = models.CharField(max_length=60)

    def __str__(self) -> str:
        return self.name


class KnowledgeBase(models.Model):
    """База знаний"""
    title = models.CharField(max_length=200)
    solution = models.TextField("Решение")
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE, null=False)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return self.title


class New(models.Model):
    """Новости"""
    title = models.CharField(max_length=200)
    content = models.TextField("Контент")
    image = models.ImageField("Изображение", upload_to="news/")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title

helpdesc/tickets/forms.py
from django import forms
from .models import Ticket, Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

helpdesc/tickets/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import CreateView
from .models import Ticket
from django.views.generic.detail import DetailView
from tickets.models import Ticket, Status, Priority, Theme, KnowledgeBase
from django.views.generic import ListView
from tickets.forms import CommentForm
from django.urls import reverse
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.http import JsonResponse


class CreateTicketView(CreateView):
    """Создание тикета пользователем"""
    model = Ticket
    fields = ['title', 'description']  # поля, которые будут отображаться в форме
    template_name = 'tickets/create_ticket.html'

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.created_by = self.request.user
            form.instance.status = Status.OPEN
            form.instance.priority = Priority.MEDIUM
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('tickets')


class TicketsListView(ListView):
    """Получения списка тикетов"""

    model = Ticket
    template_name = 'tickets/tickets.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_support'] = self.request.user.groups.filter(name='tech_support')
        return context
    
    def get_user_tickets(self, user):
        if user.groups.filter(name='tech_support').exists():  # Для пользователей в группе поддержки
            return Ticket.objects.filter(assigned_to=user).order_by('-created_at')
        else:  # Для всех остальных пользователей
            return Ticket.objects.filter(created_by=user).order_by('-created_at')

    def get_queryset(self):
        user_tickets = self.get_user_tickets(self.request.user)
        return user_tickets

class TicketDetail(DetailView):
    """Получение тикета"""
    model = Ticket

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_support'] = self.request.user.groups.filter(name='tech_support')
        context['form'] = CommentForm()
        return context


class CreateComment(View):
    """Добавление коммента"""
    def post(self, request, pk):
        ticket = Ticket.objects.get(id=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.ticket = ticket
            comment.author = request.user
            comment.save()
        
        return redirect(reverse('tickets'))


class CloseTicket(View):
    """Закрытие тикета"""
    def post(self, request, pk):
        is_updated = Ticket.objects.filter(id=pk).update(status=Status.CLOSED)
        ticket = Ticket.objects.get(id=pk)
        # Сохраняем данные в сессию
        request.session['ticket_title'] = ticket.title
        request.session['ticket_description'] = ticket.description
        return redirect(reverse('create_knowledge'))


class CreateKnowledge(CreateView):
    """Создание записи в базе знаний"""
    model = KnowledgeBase
    fields = ['title', 'solution', 'theme']
    template_name = 'tickets/create_knowledge.html'

    @method_decorator(user_passes_test(lambda user: user.groups.filter(name='tech_support').exists()))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CreateKnowledge, self).get_context_data(**kwargs)
        context['themes'] = Theme.objects.all()
        
        # Получаем данные закрытого тикета из сессии и передаем их в форму
        ticket_title = self.request.session.get('ticket_title')
        ticket_description = self.request.session.get('ticket_description')
        print(ticket_title)
        print(ticket_description)
        if ticket_title and ticket_description:
            context['form'] = self.get_form(self.form_class)  # Используем функцию get_form для получения формы
            context['form'].fields['title'].initial = ticket_title
            context['form'].fields['solution'].initial = ticket_description
        
        print(context)
        return context


    def get_success_url(self):
        return reverse_lazy('tickets')  # Правильный URL для перенаправления


def get_themes(request):
    topics = Theme.objects.all().values('id', 'name')  # Получаем данные в виде списка словарей
    return JsonResponse(list(topics), safe=False)


class KnowledgesListView(ListView):
    """Получение списка базы знаний"""

    model = KnowledgeBase
    template_name = 'tickets/knowledges.html'
    paginate_by = 4
    
    def get_user_knowledges(self, request):
        return KnowledgeBase.objects.filter(theme=request.GET.get("id")).order_by('-id')

    def get_queryset(self):
        knowledges = self.get_user_knowledges(self.request)
        return knowledges
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['theme'] = Theme.objects.get(id=self.request.GET.get("id"))
        return context


class ChangeStatusToInProgress(View):
    """Взять тикет в работу"""
    def post(self, request, pk):
        is_updated = Ticket.objects.filter(id=pk).update(status=Status.IN_PROGRESS)
        return redirect(reverse('tickets'))

helpdesc/tickets/templates/tickets/create_knowledge.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="text-center mb-4">Создание отчета</h2>
    
    <div class="d-flex justify-content-center align-items-center">
      <form method="post" action="{% url 'create_knowledge' %}" class="w-50 mx-auto"> 
        {% csrf_token %}
        <div class="form-group mb-3"> 
            <label for="id_title">Проблема:</label>
            <input id="id_title" type="text" class="form-control mb-3" placeholder="Наименование" name="title" value="{{ form.title.value }}">
            
            <label for="id_solution">Решение:</label>
            <input id="id_solution" type="text" class="form-control form-control-lg mb-3" placeholder="Решение" name="solution" value="{{ form.solution.value }}">
            
            <label for="id_theme">Выбрать тему:</label>
            <select id="id_theme" name="theme">
                {% for theme in themes %}
                    <option value="{{ theme.id }}">{{ theme.name }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-secondary mt-3">Создать отчет</button>
    </form>
    </div>
</div>
{% endblock %}

helpdesc/tickets/templates/tickets/create_ticket.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="text-center mb-4">Создание тикета</h2>
    
    <div class="d-flex justify-content-center align-items-center">
      <form method="post" action="{% url 'create_ticket' %}" class="w-50 mx-auto"> 
        {% csrf_token %}
        <div class="form-group mb-3"> 
            {% for field in form %}
                {% if field.label == "Title" %}
                    <input type="text" class="form-control mb-3" id="floatingInput" placeholder="Наименование" name="{{ field.name }}"> <!-- Добавлен класс mb-3 для отступа снизу -->
                {% elif field.label == 'Описание' %}
                    <input type="text" class="form-control form-control-lg mb-3" id="floatingInput" placeholder="{{ field.label }}" name="{{ field.name }}"> <!-- Добавлен класс mb-3 для отступа снизу -->
                {% else %}
                    <input type="text" class="form-control mb-3" id="floatingInput" placeholder="{{ field.label }}" name="{{ field.name }}"> <!-- Добавлен класс mb-3 для отступа снизу -->
                {% endif %}
            {% endfor %}
        </div>
        <button class="btn btn-secondary mt-3">Создать тикет</button> <!-- Оставляем отступ сверху после всех полей ввода -->
    </form>
    
    
    </div>
</div>
{% endblock %}

helpdesc/tickets/templates/tickets/knowledges.html
{% extends 'base.html' %}

{% block styles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
{% endblock %}

{% block content %}

<div class="container d-flex justify-content-center align-items-center">
    <div>
      <h5>{{ theme.name }}</h5>
    </div>
  </div>
  

<div class="container mt-4">
    <div class="row">
        {% for know in object_list %}
            <div class="col-md-6">
                <div class="card mb-4 shadow">
                    <div class="card-body">
                        <h5 class="card-title">Проблема: {{ know.title }}</h5>
                        <p class="card-text">Решение: {{ know.solution }}</p>
                        <p class="card-text">Кто решил: {{ know.author }}</p>
                    </div>
                </div>
            </div>
            {% if forloop.counter|divisibleby:2 %}
                </div><div class="row">
            {% endif %}
        {% endfor %}
    </div>
</div>

{% include "tickets/ticket_pagination.html" %}

{% endblock %}

helpdesc/tickets/templates/tickets/ticket_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4 pl-0">
    <h2>Подробная информация по тикету:</h2>
    <!-- Весь ваш существующий код здесь -->
</div>

<div class="container mt-4">
    <div class="row">
        <div class="col-md-8">
            <div class="card shadow">
                <div class="card-header d-flex justify-content-between">
                    <strong>{{ ticket.title }}</strong>
                    {% if ticket.get_status_display == 'Closed' %}
                        <h5>Тикет закрыт!</h5>
                    {% elif ticket.get_status_display == 'Open' and is_support %}
                        <form action="{% url 'inprogress' ticket.id %}" method="post">
                            {% csrf_token %}
                          <button class="btn btn-link" type="submit">В работу</button>
                        </form>
                    {% elif ticket.get_status_display == 'In Progress' and is_support %}
                        <form method="post" action="{% url 'close_ticket' ticket.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link">Закрыть тикет</button>
                        </form>
                    {% elif not is_support %}
                    <form method="post" action="{% url 'close_ticket' ticket.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link">Закрыть тикет</button>
                    </form>
                    {% endif %}
                </div>
                
                <div class="card-body">
                    <div class="row">
                        <div class="col-6 text-right">
                            <strong>Описание:</strong>
                        </div>
                        <div class="col-6 text-left">
                            {{ ticket.description }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 text-right">
                            <strong>Статус:</strong>
                        </div>
                        <div class="col-6 text-left">
                            {{ ticket.get_status_display }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 text-right">
                            <strong>Приоритет:</strong>
                        </div>
                        <div class="col-6 text-left">
                            {{ ticket.get_priority_display }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 text-right">
                            <strong>Создатель:</strong>
                        </div>
                        <div class="col-6 text-left">
                            {{ ticket.created_by }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 text-right">
                            <strong>Исполнитель:</strong>
                        </div>
                        <div class="col-6 text-left">
                            {{ ticket.assigned_to }}
                        </div>
                    </div>
                </div>
                <div class="card-footer text-muted">
                    Тикет создан {{ ticket.created_at }}
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-header">
                    Добавить комментарий
                </div>
                <div class="card-body">
                    <form method="post" action="{% url 'create_comment' pk=ticket.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            {% for field in form %}
                                <input type="text" class="form-control" id="floatingInput" placeholder="Введите комментарий" name="{{ field.name }}">
                            {% endfor %}
                        </div>
                        <br>
                        <button class="btn btn-secondary" type="submit">Добавить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-8">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z"/>
            </svg> 
            Комментарии: 
            <ul class="list-group text-center">
                {% for comment in ticket.comments.all %}
                <br>
                    <li class="list-group-item">
                        <div class="d-flex align-items-center">
                            <span class="me-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z"/>
                                </svg>
                            </span>
                            <strong>{{ comment.author }}:</strong> <span style="padding-left: 10px;">{{ comment.content }}</span>

                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>




{% endblock %}

helpdesc/tickets/templates/tickets/ticket_pagination.html
<div class="d-flex justify-content-center">
    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link text-secondary" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link text-secondary">Предыдущая</span>
                </li>
            {% endif %}
            
            {% for num in page_obj.paginator.page_range %}
                {% if num == page_obj.number %}
                    <li class="page-item active">
                        <span class="page-link text-light border border-dark" style="background-color: #6c757d">{{ num }}</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link text-secondary" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link text-secondary" href="?page={{ page_obj.next_page_number }}">Следующая</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>

helpdesc/tickets/templates/tickets/tickets.html
{% extends 'base.html' %}

{% block content %}

<div class="container d-flex justify-content-center align-items-center">
    <div>
      <h3>Доступные тикеты</h3>
    </div>
    <div class="ms-4"> <!-- Отступ между элементами справа (0.5rem) -->
      {% if not is_support %}
        <a href="{% url 'create_ticket' %}" class="btn btn-secondary">Создать тикет</a>
      {% endif %}
    </div>
  </div>
  
  

<br>

<div class="container overflow-hidden">
    <div class="row gy-5 mb-4">
        <div class="col">
            <h5>Open</h5>
            {% for ticket in object_list %}
                {% if ticket.status == "open" %}
                    <div class="card bg-light shadow mb-4">
                        <div class="card-body text-center">
                            <h5 class="card-title">Проблема: {{ ticket.title }}</h5>
                            <p class="card-text">
                                Создатель: {{ ticket.created_by }}<br>
                                Исполнитель: {{ ticket.assigned_to }}
                            </p>
                            <a href="{% url 'detail_ticket' ticket.id %}" class="btn btn-secondary">Детальная информация</a>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="col">
            <h5>In Progress</h5>
            {% for ticket in object_list %}
                {% if ticket.status == "in_progress" %}
                    <div class="card bg-light shadow mb-4">
                        <div class="card-body text-center">
                            <h5 class="card-title">Проблема: {{ ticket.title }}</h5>
                            <p class="card-text">
                                Создатель: {{ ticket.created_by }}<br>
                                Исполнитель: {{ ticket.assigned_to }}
                            </p>
                            <a href="{% url 'detail_ticket' ticket.id %}" class="btn btn-secondary">Детальная информация</a>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="col">
            <h5>Closed</h5>
            {% for ticket in object_list %}
                {% if ticket.status == "closed" %}
                    <div class="card bg-light shadow mb-4">
                        <div class="card-body text-center">
                            <h5 class="card-title">Проблема: {{ ticket.title }}</h5>
                            <p class="card-text">
                                Создатель: {{ ticket.created_by }}<br>
                                Исполнитель: {{ ticket.assigned_to }}
                            </p>
                            <a href="{% url 'detail_ticket' ticket.id %}" class="btn btn-secondary">Детальная информация</a>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>



{% endblock %}